stages:
  - deploy

deploy:
  stage: deploy
  image: gitlab.cp.jku.at:5050/cp/dockerfiles/rsync-deploy:latest
  script:
  - echo "${SSH_PRIVATE_KEY}" > id_ed25519
  - chmod 700 id_ed25519
  - mkdir "${HOME}/.ssh"
  - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
  - ls -la
  - ssh -i id_ed25519 ${SSH_USER_HOST} "mkdir -p ${LOCATION} && chown recvis:recvis ${LOCATION} && ls -la ${LOCATION}"
  - ssh ${SSH_USER_HOST} -i id_ed25519 "systemctl restart recvis_be"
  only:
  - main